### ISSUE TITLE
site for "Transfer Client IP Address" returns 404

### ISSUE THREAD

**Issue by krankkkk** [opentelekomcloud-docs/docsportal#184]
ELB -> Summary 

The ?-Help Hover of `Transfer Client IP Address` links to `https://docs.otc.t-systems.com/en-us/usermanual/elb/elb_ug_jt_0515.html` which doesn't seem to exist.

Same within the Edit dialog

**Comment by vladimirhasko** [comment]
Thanks for spotting this discrepancy.
We will look at it
@lhajba please look for missing document or ask our devs to change the reference on UI to proper documentation at:
https://docs.otc.t-systems.com/en-us/usermanual/elb/elb_ug_jt_0514.html

**Comment by lhajba** [comment]
hi @krankkkk 
The issue was fixed.

**Comment by krankkkk** [comment]
@vladimirhasko @lhajba 
As far as I can see it is still broken with a 404

**Comment by tischrei** [comment]
Where did you find the link? Can you create a screenshot?

**Comment by krankkkk** [comment]
@tischrei 
ELB -> Any ELB -> Any Listener -> Hover of (?) from "Transfer Client OP Address"
![image](https://github.com/user-attachments/assets/6b19b3b7-679b-462b-96d5-01aeba5f422b)

And in the same view, top right "Edit" 
![image](https://github.com/user-attachments/assets/37b2e4a5-a7e4-4bc1-b330-6d029431e951)

**Comment by lhajba** [comment]
You should see correct link, so please check if this is not caused by proxy cache on your side.

**Comment by krankkkk** [comment]
It's not, this is the currently deployed version on console.otc.t-systems.com
I can replicate this over every browser and there is no proxy-cache on my side between your site.

![image](https://github.com/user-attachments/assets/8677ca07-bb31-421f-a6a4-bfe9884dcf1e)

**Comment by tischrei** [comment]
![image](https://github.com/user-attachments/assets/fd9a5080-d4b0-49fe-b94b-a42756390831)
@krankkkk it is available on my browser. Can you verify?
